### ISSUE TITLE
Soulus' Skewer crashes game

### ISSUE THREAD

**Issue by Vhisarion** [al132mc/Volcano-Block#46]
User lukasvac#8686 on discord reported this problem today

"hi guys, while i was AFK near the  summoner farm, something happened, the game crashed and now is crashing all the time I try to load my save
'The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Ticking block entity'
any advice?
according to crash log it has to do something with Skewer"

Here's the crash log: 
[crash-2019-06-21_12.22.33-server.txt](https://github.com/al132mc/Volcano-Block/files/3314837/crash-2019-06-21_12.22.33-server.txt)

**Comment by al132mc** [comment]
https://github.com/Yuudaari/soulus/issues/77

**Comment by Yuudaari** [comment]
Hey @Vhisarion, I've made a change that should fix this issue, but I'm not 100% sure about it since I didn't reproduce on my end. Would you mind replacing your soulus.jar (`your minecraft directory/mods/Soulus-1.12.2-4.2.1-4e33621.jar`) with the one on the latest release:
https://github.com/Yuudaari/soulus/releases/tag/v4.2.2

Let me know if this fixes your issue. If it does I'll be uploading the jar to CurseForge shortly @al132mc

**Comment by Yuudaari** [comment]
Ah, just realised that Vhirasarion probably isn't the same person as the reporter. I can just straight upload to CurseForge if you guys would like

**Comment by al132mc** [comment]
Indeed, he isn't. I'd say just go for it and upload if you think you've fixed it

**Comment by Yuudaari** [comment]
No problem! Hope this fixes it. Looks like [the file's been approved](https://minecraft.curseforge.com/projects/soulus/files/2727687).

**Comment by al132mc** [comment]
I'll just assume this has been fixed unless someone creates a new issue
